ข้อ1.

In [81]:

def walk_pattern(n):
    res = [0] * (n + 2)  
    res[0] = 1
    res[1] = 1
    res[2] = 2

    for i in range(2, n + 1):
        res[i] = res[i - 1] + res[i - 2]

    return res[n]



n = 4
print("มีทั้งหมด : ",walk_pattern(n))

มีทั้งหมด :  5


ช้อที่2

In [82]:
import numpy as np
def maxWater(arr, n):
  counts = 0
  total = 0.0
  h=np.zeros_like(arr, dtype='float32')
  h_check=np.zeros_like(arr, dtype='float32')
  index = 0.0
  lowest_g = np.zeros_like(arr)
  check =len(arr)
  while(total-n != 0):   #วนลูปจนกว่า น้ำ(n) จะหมด
      for c_low in range(len(arr)):

        index = arr.index(min((arr)))  #หาindex ที่ต่ำที่สุดปัจจุบัน
        if(arr[c_low]<=arr[index]):
         lowest_g[c_low] = 1  #ระบุตำแหน่งที่ตำสุดลง ใน array
        if lowest_g[c_low] ==1 :
          counts = counts+1
        check = check-1
        if(check == 0):     #เท่ากับรอบสุดท้าย
          add_val = 1/counts
          #update ค่า h
          for p in range(len(arr)):
            if(lowest_g[p]==1):
              h[p]=h[p]+add_val
              h_check[p] = h_check[p]+add_val
              arr[p]=arr[p]+h[p]
              h[p]=0
              # print(lowest_g)
              lowest_g[p] =0

         # print(lowest_g)
          # print('h ปัจจุบัน =',h_check)
          # print('ความสูงดิน+น้ำ',arr)
          check = len(arr)
      counts=0
      total = total+1
  print('ค่าความสูงของแต่ละคอลัมน์ เท่ากับ' ,arr+h)
  print('ค่าความสูงของน้ำที่วัดจากพื้นของแต่ละคอลัมน์ เท่ากับ ',h_check)
  print('คอลัมน์ที่สูงที่สุดวัดจากพื้นถึงผิวน้ำ เท่ากับ',max(h_check))
  print()
  print('----------------------------------------')







exam_1 = [3,5,4,5,2]
exam_2 = [1,4,3,6]
maxWater(exam_1,11)
maxWater(exam_2,5)


ค่าความสูงของแต่ละคอลัมน์ เท่ากับ [6.00000006 6.         6.00000006 6.         6.00000006]
ค่าความสูงของน้ำที่วัดจากพื้นของแต่ละคอลัมน์ เท่ากับ  [2.9999998 1.        2.        1.        3.9999995]
คอลัมน์ที่สูงที่สุดวัดจากพื้นถึงผิวน้ำ เท่ากับ 3.9999995

----------------------------------------
ค่าความสูงของแต่ละคอลัมน์ เท่ากับ [4.33333334 4.33333334 4.33333334 6.        ]
ค่าความสูงของน้ำที่วัดจากพื้นของแต่ละคอลัมน์ เท่ากับ  [3.3333333  0.33333334 1.3333334  0.        ]
คอลัมน์ที่สูงที่สุดวัดจากพื้นถึงผิวน้ำ เท่ากับ 3.3333333

----------------------------------------


ข้อที่3


In [83]:
from re import I
def trap_water(arr):
    n = len(arr)
    water_level = [0] * (n+1) #เพราะว่าจะเริ่มที่ด้านนอกกำแพงเป็น0 เลยต้องกำหนดขนาดarray ให้เกินมาซ้าย+1 ขวา+1 =2
    left_max = [0]*(n)
    right_max = [0]*(n)
    maxl=maxr = 0

    left_max[0] = arr[0]
    for i in range(1, n):        #หา Leftmax ให้ได้ index ไว้เทียบ ตอนเรียงละดับน้ำ
        left_max[i] = max(left_max[i - 1], arr[i])
    right_max[n - 1] = arr[n - 1]

    for i in range(n - 2, -1, -1):  #หา rightmax ให้ได้ index ไว้เทียบ ตอนเรียงละดับน้ำ
        right_max[i] = max(right_max[i + 1], arr[i])

    for i  in range (n):
      if maxl < arr[i]:  #เริ่มเรียงระดับน้ำจากซ้ายถ้ายังไม่เจอกำแพงที่ต่ำกว่าสามารถให้บรรจุ เท่ากับ ขนาดmaxl ปัจจุบัน
        water_level[i] = maxl
        maxl = arr[i]     #อัปเดต maxl
      elif maxl == left_max[i] and left_max[i] <= right_max[i]: # ถ้าเจอกำแพงต่ำกว่า จะเทียบกับ array left_max แทนเพื่อเติมน้ำให้เท่ากับค่าสูงสุดก่อน
        water_level[i+1] = right_max[i]
      else:                       #กรณีเจอกำแพงต่ำกว่าและยังมีกำแพงต่อๆไปที่สูงกว่าปัจจุบัน
        water_level[i] = maxl
    for i in range(n-1,-1,-1):
      if maxr < arr[i]:    #เริ่มเรียงจากขวาจนกว่าจะเจอกำแพงต่ำกว่าเหมือนด้านบน
        water_level[i+1] = maxr       #i+1 เพราะอาเรย์ loop i ไม่ถึงตัวสุดท้าย
        maxr=arr[i]
      elif maxr == right_max[i+1] and right_max[i] <=left_max[i]:        #กำแพงต่ำกว่าเทียบกับ right_max
        # print('รอบที่ ',i+1,'= ',right_max[i+1])
        water_level[i+1] = maxr
      else:
        water_level[i+1] = left_max[i]
      if i == 0 :             #เพื่อกันตอนใส่น้ำจากขวามาซ้ายจะเปลี่ยนระดับน้ำตัวแรกให้เป็นค่าที่ผิด
        if(arr[i+1]>arr[i]):
          water_level[i+1]=arr[i]       #ถ้าสรุปว่ากำแพงตัวแรกต่ำกว่ากำแพงที่2 ให่ทำให้ระดับสูงได้แค่เท่ากำแพงแรก

    # print('left max = ',left_max)
    # print('right max = ',right_max)
    water_level.pop(0)       # เพราะหัวท้ายเป็น0 อยู่แล้วจากการเช็ค maxl,maxr
    water_level.pop(n-1)


    print('input = ',arr)
    print('output = ',water_level)
    print('-------------------')



exp_1 = [3,5,4,5,2]
exp_2=[6,5,4,1,3,2]
test= [1,7,2,6,4,8]
test2=[1,9,9,4,6,2,6,6,1,4,2]


#น่าจะถูกทุกกรณี

trap_water(test)
trap_water(test2)
trap_water(exp_1)
trap_water(exp_2)


input =  [1, 7, 2, 6, 4, 8]
output =  [1, 7, 7, 7, 7]
-------------------
input =  [1, 9, 9, 4, 6, 2, 6, 6, 1, 4, 2]
output =  [1, 9, 6, 6, 6, 6, 6, 4, 4, 2]
-------------------
input =  [3, 5, 4, 5, 2]
output =  [3, 5, 5, 2]
-------------------
input =  [6, 5, 4, 1, 3, 2]
output =  [5, 4, 3, 3, 2]
-------------------


ข้อที่4

In [84]:
import numpy as np
def sec_room(n,arr):
  if(len(arr)!= n):
    return print('โปรดระบุจำนวนห้องให้ถูกต่้อง')
  arr_order = np.zeros_like(arr)  #เก็บตำแหน่งที่ถูกใช้แล้ว
  present_arr = arr[:]
  answer = np.full_like(arr,3)
  answer_str = ['ว่าง']*len(arr)
  counts = 0
  free_room = 0
  max_arr = max(arr)
  while(counts <n):
      counts = counts+1
      min_index = present_arr.index(min(present_arr))
      if(present_arr[min_index]<=max_arr):
        arr_order[min_index] = 1
        present_arr[min_index] = max_arr+1
      for i in range(len(arr)):        #ลูปหา free_room
        if(i == 0):     #กรณีที่อยู่ชิดขอบซ้าย
          if(arr_order[i] == 0 and arr_order[i+1] == 0 ):
            free_room = free_room+1
        elif(i ==len(arr)-1):  #กรณีชิดขอบขวา
          if(arr_order[i-1] ==0 and arr_order[i]==0):
            free_room = free_room+1
        elif (i == 1 ): #ถัดจากกล่องแรก
          if(arr_order[i-1]== 0 and arr_order[i]== 1):
            free_room = free_room+1
        elif (i == len(arr)-2 ): #ถัดจากกล่องสุดท้าย
          if(arr_order[i+1]== 0 and arr_order[i]== 1):
            free_room = free_room+1
        elif(i >= 2 and i <= len(arr)-3):
          if((arr_order[i-1] == 0 and arr_order[i+1] == 0) and arr_order[i]== 0):
              free_room = free_room+1
      if(min_index <len(arr)):              #กัน out of bound
        if(min_index == 0 or min_index ==len(arr)-1): #ส่่วนแบ่งประเภทผู้ใช้
            if(min_index == 0): #เช็คฝั่งซ้ายสุด
              if((arr_order[min_index+1] == 0  and free_room >=1) ):
                answer[min_index] = 0
              elif((arr_order[min_index+1] == 1 and free_room == 0)):
                answer[min_index] = 1
              elif((arr_order[min_index+1] == 1 and free_room >=1 )):
                answer[min_index] =2
            elif(min_index==len(arr)-1):  #เช็คฝั่งขวาสุด
              if((arr_order[min_index-1] == 0  and free_room >=1)):
                answer[min_index] = 0
              elif((arr_order[min_index-1] == 1 and free_room == 0)):
                answer[min_index] = 1
              elif((arr_order[min_index-1] == 1 and free_room >=1 )):
                answer[min_index] =2
        elif((arr_order[min_index+1] == 1 and arr_order[min_index-1] ==1) and free_room ==0 ): ######################ด้านใน
            answer[min_index] = 1
        elif((arr_order[min_index+1] == 1 or arr_order[min_index-1] ==1) and free_room >=1 ):
            answer[min_index] = 2
            free_room=0
        elif(min_index > 1 and min_index<len(arr)-2)  :
          if(((arr_order[min_index+1] == 0 and arr_order[min_index-1]) ==0 and free_room >=1)):
            answer[min_index] = 0
          elif((arr_order[min_index+1] == 1 or arr_order[min_index-1] ==1) and free_room <= 0  ):
              answer[min_index] = 1
          elif((arr_order[min_index+1] == 1 or arr_order[min_index-1] ==1) and free_room >= 1 ):
              answer[min_index] = 2
      answer_str[min_index] = 'เข้าใช้'  #print ก่อนเปลี่ยนค่า
      print(answer)
      print('แผนผังห้องประชุม',answer_str) #เช็คOutput สถานะห้อง
      answer_str[min_index] = 'ไม่ว่าง'
      free_room=0
  print('คำตอบสุดท้ายเท่ากับ',answer)
room = [5,4,1,3,2]
sec_room(5,room) #########################       3ในlist ใส่ไว้ให้รู้ว่ายังไม่กำหนดว่าผู้ใช้เป็นผู้ต้องสงสัยประเภทใด (1,2,3)


[3 3 0 3 3]
แผนผังห้องประชุม ['ว่าง', 'ว่าง', 'เข้าใช้', 'ว่าง', 'ว่าง']
[3 3 0 3 0]
แผนผังห้องประชุม ['ว่าง', 'ว่าง', 'ไม่ว่าง', 'ว่าง', 'เข้าใช้']
[3 3 0 2 0]
แผนผังห้องประชุม ['ว่าง', 'ว่าง', 'ไม่ว่าง', 'เข้าใช้', 'ไม่ว่าง']
[3 2 0 2 0]
แผนผังห้องประชุม ['ว่าง', 'เข้าใช้', 'ไม่ว่าง', 'ไม่ว่าง', 'ไม่ว่าง']
[1 2 0 2 0]
แผนผังห้องประชุม ['เข้าใช้', 'ไม่ว่าง', 'ไม่ว่าง', 'ไม่ว่าง', 'ไม่ว่าง']
คำตอบสุดท้ายเท่ากับ [1 2 0 2 0]
